/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercado.view;

import com.mycompany.supermercado.model.Perecedero;
import com.mycompany.supermercado.servicios.ServicioSupermercado;
import java.util.List;

/**
 *
 * @author Alexander
 */
public class GUICalcularPerecedero extends javax.swing.JFrame {
    
    private ServicioSupermercado servicioSupermercado;
    
    /**
     * Creates new form GUICalcularPerecedero
     */
    public GUICalcularPerecedero(ServicioSupermercado servicio) {
        this.servicioSupermercado = servicio;
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        lblTotalPrecios = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblStaticPorcentaje = new javax.swing.JLabel();
        ftxtTotalPrecios = new javax.swing.JFormattedTextField();
        btnCalcular = new javax.swing.JButton();
        ftxtIVA = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcular Balance Perecedero");
        setPreferredSize(new java.awt.Dimension(440, 400));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("BALANCE DE CUENTAS");

        lblInformacion.setText("Sumatoria de precios de todos los productos con el IVA agregado");

        lblTotalPrecios.setText("Total de precios:");

        lblIVA.setText("IVA a aplicar:");

        lblStaticPorcentaje.setText("%");

        ftxtTotalPrecios.setEditable(false);
        ftxtTotalPrecios.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        ftxtTotalPrecios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ftxtTotalPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtTotalPreciosActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(255, 153, 51));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        ftxtIVA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        ftxtIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ftxtIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtIVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInformacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalPrecios)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftxtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStaticPorcentaje)
                        .addGap(66, 66, 66))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(ftxtTotalPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addComponent(lblInformacion)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(ftxtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStaticPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(lblTotalPrecios)
                .addGap(25, 25, 25)
                .addComponent(ftxtTotalPrecios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcular)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double IVA = 0.0;
        double IVAcalculado = 0.0;
        double resultado = 0.0;
        List<Perecedero> perecederos;
        
        IVA = Double.parseDouble(ftxtIVA.getValue().toString().replace(',', '.'));
        IVA /= 100;
        perecederos = servicioSupermercado.listarPerecedero();
        for (Perecedero perecedero : perecederos) {
            resultado += perecedero.getPrecio() * perecedero.getCantidad();
        }
        IVAcalculado = resultado * IVA;
        resultado += IVAcalculado;
        
        ftxtTotalPrecios.setValue(resultado);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void ftxtTotalPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtTotalPreciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtTotalPreciosActionPerformed

    private void ftxtIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtIVAActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JFormattedTextField ftxtIVA;
    private javax.swing.JFormattedTextField ftxtTotalPrecios;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblStaticPorcentaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalPrecios;
    // End of variables declaration//GEN-END:variables
}
