/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.supermercado.view;

import com.mycompany.supermercado.servicios.ServicioSupermercado;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;


/**
 *
 * @author Alexander
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private ServicioSupermercado servicioSupermercado;
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        this.servicioSupermercado = new ServicioSupermercado();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRazonSocial = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemArchivoSalir = new javax.swing.JMenuItem();
        menuPerecedero = new javax.swing.JMenu();
        itemPerecederoAdicionar = new javax.swing.JMenuItem();
        itemPerecederoBuscar = new javax.swing.JMenuItem();
        itemPerecederoCalcular = new javax.swing.JMenuItem();
        itemPerecederoEliminar = new javax.swing.JMenuItem();
        itemPerecederoListar = new javax.swing.JMenuItem();
        separadorPerecedero = new javax.swing.JPopupMenu.Separator();
        itemDesechoAdicionar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuNoPerecedero = new javax.swing.JMenu();
        itemNoPerecederoAdicionar = new javax.swing.JMenuItem();
        itemNoPerecederoBuscar = new javax.swing.JMenuItem();
        itemNoPerecederoCalcular = new javax.swing.JMenuItem();
        itemNoPerecederoEliminar = new javax.swing.JMenuItem();
        itemNoPerecederoListar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAyudaAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Supermercado Principal");
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        lblRazonSocial.setFont(new java.awt.Font("Rockwell", 2, 48)); // NOI18N
        lblRazonSocial.setForeground(new java.awt.Color(255, 153, 102));
        lblRazonSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRazonSocial.setText("Supermercado \"Donde los electrónicos\"");

        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        itemArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        itemArchivoSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemArchivoSalir.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_salir.png")));
        itemArchivoSalir.setText("Salir");
        itemArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemArchivoSalir);

        menuBarPrincipal.add(menuArchivo);

        menuPerecedero.setText("Perecedero");
        menuPerecedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuPerecedero.setMargin(new java.awt.Insets(6, 6, 6, 6));

        itemPerecederoAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPerecederoAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPerecederoAdicionar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_agregar.png")));
        itemPerecederoAdicionar.setText("Adicionar producto");
        itemPerecederoAdicionar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemPerecederoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPerecederoAdicionarActionPerformed(evt);
            }
        });
        menuPerecedero.add(itemPerecederoAdicionar);

        itemPerecederoBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPerecederoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPerecederoBuscar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_buscar.png")));
        itemPerecederoBuscar.setText("Buscar producto");
        itemPerecederoBuscar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemPerecederoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPerecederoBuscarActionPerformed(evt);
            }
        });
        menuPerecedero.add(itemPerecederoBuscar);

        itemPerecederoCalcular.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPerecederoCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPerecederoCalcular.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_calcular.png")));
        itemPerecederoCalcular.setText("Calcular producto");
        itemPerecederoCalcular.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemPerecederoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPerecederoCalcularActionPerformed(evt);
            }
        });
        menuPerecedero.add(itemPerecederoCalcular);

        itemPerecederoEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPerecederoEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPerecederoEliminar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_eliminar.png")));
        itemPerecederoEliminar.setText("Eliminar producto");
        itemPerecederoEliminar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemPerecederoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPerecederoEliminarActionPerformed(evt);
            }
        });
        menuPerecedero.add(itemPerecederoEliminar);

        itemPerecederoListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemPerecederoListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemPerecederoListar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_listar.png")));
        itemPerecederoListar.setText("Listar productos");
        itemPerecederoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPerecederoListarActionPerformed(evt);
            }
        });
        menuPerecedero.add(itemPerecederoListar);
        menuPerecedero.add(separadorPerecedero);

        itemDesechoAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemDesechoAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemDesechoAdicionar.setText("Adicionar desecho");
        menuPerecedero.add(itemDesechoAdicionar);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Actualizar desecho");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuPerecedero.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Eliminar desecho");
        menuPerecedero.add(jMenuItem2);

        menuBarPrincipal.add(menuPerecedero);

        menuNoPerecedero.setText("No Perecedero");
        menuNoPerecedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        itemNoPerecederoAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNoPerecederoAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemNoPerecederoAdicionar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_agregar.png")));
        itemNoPerecederoAdicionar.setText("Adicionar producto");
        itemNoPerecederoAdicionar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemNoPerecederoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoPerecederoAdicionarActionPerformed(evt);
            }
        });
        menuNoPerecedero.add(itemNoPerecederoAdicionar);

        itemNoPerecederoBuscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNoPerecederoBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemNoPerecederoBuscar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_buscar.png")));
        itemNoPerecederoBuscar.setText("Buscar producto");
        itemNoPerecederoBuscar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemNoPerecederoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoPerecederoBuscarActionPerformed(evt);
            }
        });
        menuNoPerecedero.add(itemNoPerecederoBuscar);

        itemNoPerecederoCalcular.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNoPerecederoCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemNoPerecederoCalcular.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_calcular.png")));
        itemNoPerecederoCalcular.setText("Calcular producto");
        itemNoPerecederoCalcular.setMargin(new java.awt.Insets(6, 6, 6, 6));
        menuNoPerecedero.add(itemNoPerecederoCalcular);

        itemNoPerecederoEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNoPerecederoEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemNoPerecederoEliminar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_eliminar.png")));
        itemNoPerecederoEliminar.setText("Eliminar producto");
        itemNoPerecederoEliminar.setMargin(new java.awt.Insets(6, 6, 6, 6));
        itemNoPerecederoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoPerecederoEliminarActionPerformed(evt);
            }
        });
        menuNoPerecedero.add(itemNoPerecederoEliminar);

        itemNoPerecederoListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemNoPerecederoListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemNoPerecederoListar.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_listar.png")));
        itemNoPerecederoListar.setText("Listar productos");
        itemNoPerecederoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNoPerecederoListarActionPerformed(evt);
            }
        });
        menuNoPerecedero.add(itemNoPerecederoListar);

        menuBarPrincipal.add(menuNoPerecedero);

        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        itemAyudaAcerca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemAyudaAcerca.setIcon(new ImageIcon(getClass().getClassLoader().getResource("icons/icon_info.png")));
        itemAyudaAcerca.setText("Acerca de...");
        itemAyudaAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaAcercaActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAyudaAcerca);

        menuBarPrincipal.add(menuAyuda);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(663, Short.MAX_VALUE)
                .addComponent(lblRazonSocial)
                .addGap(396, 396, 396))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(lblRazonSocial)
                .addContainerGap(639, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArchivoSalirActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_itemArchivoSalirActionPerformed

    private void itemAyudaAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrollado por: \nAlejandro Vargas, Leandro Vergara, Jhon Cartagena.  \nVersión del aplicativo: 1.0", "Aviso legal", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemAyudaAcercaActionPerformed

    private void itemPerecederoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerecederoEliminarActionPerformed
        GUIEliminarPerecedero gUIEliminarPerecedero = new GUIEliminarPerecedero(servicioSupermercado);
        gUIEliminarPerecedero.setVisible(true);
    }//GEN-LAST:event_itemPerecederoEliminarActionPerformed

    private void itemNoPerecederoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoPerecederoEliminarActionPerformed
        GUIEliminarNoPerecedero gUIEliminarNoPerecedero = new GUIEliminarNoPerecedero(servicioSupermercado);
        gUIEliminarNoPerecedero.setVisible(true);
    }//GEN-LAST:event_itemNoPerecederoEliminarActionPerformed

    private void itemPerecederoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerecederoAdicionarActionPerformed
        GUIAdicionarPerecedero guiPerecedero = new GUIAdicionarPerecedero(servicioSupermercado);
        guiPerecedero.setVisible(true);
    }//GEN-LAST:event_itemPerecederoAdicionarActionPerformed

    private void itemNoPerecederoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoPerecederoAdicionarActionPerformed
        GUIAdicionarNoPerecedero guiNoPerecedero = new GUIAdicionarNoPerecedero(servicioSupermercado);
        guiNoPerecedero.setVisible(true);
    }//GEN-LAST:event_itemNoPerecederoAdicionarActionPerformed

    private void itemPerecederoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerecederoListarActionPerformed
        GUIListarPerecedero gUIListarPerecedero = new GUIListarPerecedero(servicioSupermercado);
        gUIListarPerecedero.setVisible(true);
    }//GEN-LAST:event_itemPerecederoListarActionPerformed

    private void itemNoPerecederoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoPerecederoListarActionPerformed
        GUIListarNoPerecedero gUIListarNoPerecedero = new GUIListarNoPerecedero(servicioSupermercado);
        gUIListarNoPerecedero.setVisible(true);
    }//GEN-LAST:event_itemNoPerecederoListarActionPerformed

    private void itemPerecederoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerecederoBuscarActionPerformed
        GUIBuscarPerecedero gUIBuscarPerecedero = new GUIBuscarPerecedero(servicioSupermercado);
        gUIBuscarPerecedero.setVisible(true);
        
    }//GEN-LAST:event_itemPerecederoBuscarActionPerformed

    private void itemPerecederoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPerecederoCalcularActionPerformed
        GUICalcularPerecedero gUICalcularPerecedero = new GUICalcularPerecedero(servicioSupermercado);
        gUICalcularPerecedero.setVisible(true);
    }//GEN-LAST:event_itemPerecederoCalcularActionPerformed

    private void itemNoPerecederoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNoPerecederoBuscarActionPerformed
        GUIBuscarNoPerecedero gUIBuscarNoPerecedero = new GUIBuscarNoPerecedero(servicioSupermercado);
        gUIBuscarNoPerecedero.setVisible(true);
    }//GEN-LAST:event_itemNoPerecederoBuscarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemArchivoSalir;
    private javax.swing.JMenuItem itemAyudaAcerca;
    private javax.swing.JMenuItem itemDesechoAdicionar;
    private javax.swing.JMenuItem itemNoPerecederoAdicionar;
    private javax.swing.JMenuItem itemNoPerecederoBuscar;
    private javax.swing.JMenuItem itemNoPerecederoCalcular;
    private javax.swing.JMenuItem itemNoPerecederoEliminar;
    private javax.swing.JMenuItem itemNoPerecederoListar;
    private javax.swing.JMenuItem itemPerecederoAdicionar;
    private javax.swing.JMenuItem itemPerecederoBuscar;
    private javax.swing.JMenuItem itemPerecederoCalcular;
    private javax.swing.JMenuItem itemPerecederoEliminar;
    private javax.swing.JMenuItem itemPerecederoListar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuNoPerecedero;
    private javax.swing.JMenu menuPerecedero;
    private javax.swing.JPopupMenu.Separator separadorPerecedero;
    // End of variables declaration//GEN-END:variables
}
